# Generated by Django 6.0.6 on 2026-06-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompPago',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'comp_pago',
            },
        ),
        migrations.CreateModel(
            name='EdoFactura',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'edo_factura',
            },
        ),
        migrations.CreateModel(
            name='EdoProveedor',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'edo_proveedor',
            },
        ),
        migrations.CreateModel(
            name='EdoUsuario',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'edo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=20)),
                ('primApell', models.CharField(max_length=20)),
                ('segApell', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=13)),
                ('numCelular', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=13)),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.CASCADE, to='core.edoproveedor')),
                ('sucursal', models.ForeignKey(db_column='sucursal', on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fechaEmision', models.DateField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limitePago', models.DateField()),
                ('comprobante', models.ForeignKey(blank=True, db_column='comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comppago')),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.CASCADE, to='core.edofactura')),
                ('proveedor', models.ForeignKey(db_column='proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('proveedor', models.ForeignKey(db_column='proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('contrasena', models.CharField(db_column='contraseña', max_length=20)),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.CASCADE, to='core.edousuario')),
                ('persona', models.ForeignKey(db_column='persona', on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(db_column='factura', on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
                ('proveedor', models.ForeignKey(db_column='proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'db_table': 'factura_proveedor',
                'unique_together': {('factura', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='ReporteFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(db_column='factura', on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
                ('reporte', models.ForeignKey(db_column='reporte', on_delete=django.db.models.deletion.CASCADE, to='core.reporte')),
            ],
            options={
                'db_table': 'reporte_factura',
                'unique_together': {('reporte', 'factura')},
            },
        ),
    ]
